### PR TITLE
Implement reconnect method for streams

### PR DESCRIPTION
**Pull request by leo-p**
A new method to automatically reconnect to streams once they stop.

```console
$ deepo noop -i http://localhost/ISAPI/Streaming/channels/101/picture -o pred --stream_reconnect
[INFO 2019-10-17 13:33:47,053] Input fps of 25.0 automatically detected, but no output fps specified. Using same value for both.
[INFO 2019-10-17 13:33:47,068] Input processing: 0it [00:00, ?it/s]
[INFO 2019-10-17 13:33:47,359] Input processing: 2it [00:00,  6.89it/s]
[INFO 2019-10-17 13:33:47,755] Input processing: 4it [00:00,  5.83it/s]
[INFO 2019-10-17 13:33:48,207] Input processing: 6it [00:01,  5.27it/s]
[INFO 2019-10-17 13:33:48,605] Input processing: 8it [00:01,  5.21it/s]
[INFO 2019-10-17 13:33:49,051] Input processing: 10it [00:01,  5.05it/s]
[INFO 2019-10-17 13:33:49,522] Input processing: 12it [00:02,  4.89it/s]
[INFO 2019-10-17 13:33:49,990] Input processing: 14it [00:02,  4.79it/s]
^C[INFO 2019-10-17 13:33:50,097] Stop asked, waiting for threads to process queued messages.
[INFO 2019-10-17 13:33:50,305] Input processing: 15it [00:03,  4.64it/s]
[INFO 2019-10-17 13:33:50,305] Summary: errors=0 uncompleted=0 successful=15 total=inf.
```

### CODE REVIEW

**Comment by maingoh** [comment]
Probably we want that streams always reconnect. We can optionally disable it.

**Comment by leo-p** [comment]
> Probably we want that streams always reconnect. We can optionally disable it.

I've used mostly RTSP streams where this would make sense, but I don't know about other type of streams we support. @alemoreau ?

**Comment by maingoh** [comment]
We agreed with @alemoreau that it should be enabled by default. Though maybe just like other flags we should have a `--no_stream_reconnect`.

**Comment by leo-p** [comment]
Closed for no real functional need.

**Pull request closed without merging**
