### PR TITLE
Optional field id in format to upload images

### PR DESCRIPTION
**Pull request by Alexis-Jacob**
This PR gives the possibility to the user to upload a file without any id (or id == null)

### CODE REVIEW

**Review by maingoh — APPROVED** [review]
It would be nice to check why the test is passing with an invalid file, probably because of the `logger.error`.

**Comment by Alexis-Jacob** [comment]
> It would be nice to check why the test is passing with an invalid file, probably because of the `logger.error`.

what it's strange it's that the data are uploaded ...

**Comment by maingoh** [comment]
So I tested running only the test with the json using `pytest -k test_2e2_studio_json_upload
` and the data is not uploaded without this fix (count stays the same), as expected. Probably you felt that the data was uploaded because you were launching all studio tests which upload to the same project.
So we can merge !

**Comment by Alexis-Jacob** [comment]
> So I tested running only the test with the json using `pytest -k test_2e2_studio_json_upload ` and the data is not uploaded without this fix (count stays the same), as expected. Probably you felt that the data was uploaded because you were launching all studio tests which upload to the same project.
> So we can merge !
Damn my bad ! thanks for looking for into it

**Pull request merged**
